spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chudichen/spring-cloud/tree/master/config
          searchPaths: data

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8503