spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chudichen/spring-cloud
          search-paths: config-repo
  rabbitmq:
    host: 221.4.223.101
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8503