env:
  dev
eureka:
  client:
    service-url:
      defaultZone: http://www.test.com:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Star.123Mysql
    url: jdbc:mysql://www.test.com/sell?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=true&useSSL=true&autoReconnect=true
server:
  port: 8502

