env:
  test
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Star.123Mysql
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=true&useSSL=true&autoReconnect=true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8501